name: build

on:
  push:
    branches:    
      - build
jobs:
  build:

    env:
      BUILD_TYPE: Release

    runs-on: ubuntu-20.04

    steps:

    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install python3 libglew2.1

    - name: Checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      
    - name: Build
      run: |
        set -ex
        python3 -m venv cq-editor
        source cq-editor/bin/activate
        pip3 install --upgrade pip
        pip3 install git+https://github.com/CadQuery/cq-cli.git
        mkdir configs
        mkdir output
        python3 gen_configs.py
        python3 gen_3dfiles.py
        python3 gen_pngs.py
        rm output/*.svg
        set +ex

    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: stl
        path: |
          output/*.stl

    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: dxf
        path: |
          output/*.dxf

    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: png
        path: |
          output/*.png
          GALLERY.md

