name: build

on:
  push:
    branches:    
      - build
jobs:
  build:

    env:
      BUILD_TYPE: Release

    runs-on: ubuntu-latest

    steps:

    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install python3 libglew2.1 python3-progress

    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      
    - name: Build
      run: |
        set -ex
        wget https://github.com/CadQuery/cq-cli/releases/download/v2.2-beta.3/cq-cli-Linux-x86_64.zip
        unzip cq-cli-Linux-x86_64.zip
        chmod u+x cq-cli/cq-cli
        mkdir configs
        python3 gen_configs.py
        python3 gen_3dfiles.py
        python3 gen_pngs.py
        rm output/*.svg
        set +ex

    - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
      with:
        name: output
        path: |
          output

